# all in one now

#all:
#	python3 buildschemes.py

ahs:
	python3 buildschemes.py ../ahsks5sow/config/settings.ini

test:
	python3 tests.py

clean:
	rm -f buildschemes.log
	rm -f scheme/*html
	rm -f test_output/*.html
	rm -f *\.pyc
